### ISSUE TITLE
Use the repo name as a key instead of artifactid and groupid

### ISSUE THREAD

**Issue by tdurieux** [castor-software/jdbl-experiments#6]
artifactid and groupid can be duplicated between projects

**Comment by cesarsotovalero** [comment]
Do you mean the artifactId and groupId for the dashboard, or in JDBL?

**Comment by tdurieux** [comment]
In the jdbl execution framework.

**Comment by cesarsotovalero** [comment]
@tdurieux I can see that this issue is fixed in the dashboad :+1:
